<?php /** @var Mage_Adminhtml_Block_Template $this */ ?>
<script type="text/javascript">
document.observe("dom:loaded", function() {
    $$('.hackathon_indexerstats_progress').each(function (progressbar) {
        progressbar.progress = new IndexerStats.Progress(progressbar);
    });
    indexer_processes_grid_massactionJsObject.apply = indexer_processes_grid_massactionJsObject.apply.wrap(
        function(parent) {
            if (this.select.value == 'reindex') {
                var firstProcessId = this.checkedString.split(',', 1);
                var progressbar = $('indexer_processes_grid_table')
                    .select('input[name=process][value=' + firstProcessId + ']')[0]
                    .parentNode.parentNode
                    .select('.hackathon_indexerstats_info')[0];
                progressbar.addClassName('hackathon_indexerstats_progress');
                progressbar.parentNode.removeClassName('hackathon_indexerstats_finished');
                progressbar.progress = new IndexerStats.Progress(progressbar);
            }
            parent();
            if (this.select.value == 'reindex') {
                IndexerStats.status.update();
            }
        });
    IndexerStats.status = new IndexerStats.Status('<?php echo $this->getUrl('adminhtml/process/statusAjax') ?>');
});
</script>